/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-25 at 13:50:17 UTC 
 * Modify at your own risk.
 */

package com.appspot.dl_mytimeline.statusapi;

/**
 * Service definition for Statusapi (v1).
 *
 * <p>
 * An API to manage personal timeline status
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link StatusapiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Statusapi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the statusapi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://dl-mytimeline.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "statusapi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Statusapi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Statusapi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "add".
   *
   * This request holds the parameters needed by the statusapi server.  After setting any optional
   * parameters, call the {@link Add#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param content
   * @param timestamp
   * @return the request
   */
  public Add add(java.lang.Integer id, java.lang.String content, java.lang.Long timestamp) throws java.io.IOException {
    Add result = new Add(id, content, timestamp);
    initialize(result);
    return result;
  }

  public class Add extends StatusapiRequest<com.appspot.dl_mytimeline.statusapi.model.Status> {

    private static final String REST_PATH = "addStatus/{id}/{content}/{timestamp}";

    /**
     * Create a request for the method "add".
     *
     * This request holds the parameters needed by the the statusapi server.  After setting any
     * optional parameters, call the {@link Add#execute()} method to invoke the remote operation. <p>
     * {@link Add#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param content
     * @param timestamp
     * @since 1.13
     */
    protected Add(java.lang.Integer id, java.lang.String content, java.lang.Long timestamp) {
      super(Statusapi.this, "POST", REST_PATH, null, com.appspot.dl_mytimeline.statusapi.model.Status.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.content = com.google.api.client.util.Preconditions.checkNotNull(content, "Required parameter content must be specified.");
      this.timestamp = com.google.api.client.util.Preconditions.checkNotNull(timestamp, "Required parameter timestamp must be specified.");
    }

    @Override
    public Add setAlt(java.lang.String alt) {
      return (Add) super.setAlt(alt);
    }

    @Override
    public Add setFields(java.lang.String fields) {
      return (Add) super.setFields(fields);
    }

    @Override
    public Add setKey(java.lang.String key) {
      return (Add) super.setKey(key);
    }

    @Override
    public Add setOauthToken(java.lang.String oauthToken) {
      return (Add) super.setOauthToken(oauthToken);
    }

    @Override
    public Add setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Add) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Add setQuotaUser(java.lang.String quotaUser) {
      return (Add) super.setQuotaUser(quotaUser);
    }

    @Override
    public Add setUserIp(java.lang.String userIp) {
      return (Add) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer id;

    /**

     */
    public java.lang.Integer getId() {
      return id;
    }

    public Add setId(java.lang.Integer id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String content;

    /**

     */
    public java.lang.String getContent() {
      return content;
    }

    public Add setContent(java.lang.String content) {
      this.content = content;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long timestamp;

    /**

     */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    public Add setTimestamp(java.lang.Long timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    @Override
    public Add set(String parameterName, Object value) {
      return (Add) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getStatus".
   *
   * This request holds the parameters needed by the statusapi server.  After setting any optional
   * parameters, call the {@link GetStatus#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetStatus getStatus(java.lang.Integer id) throws java.io.IOException {
    GetStatus result = new GetStatus(id);
    initialize(result);
    return result;
  }

  public class GetStatus extends StatusapiRequest<com.appspot.dl_mytimeline.statusapi.model.Status> {

    private static final String REST_PATH = "status/{id}";

    /**
     * Create a request for the method "getStatus".
     *
     * This request holds the parameters needed by the the statusapi server.  After setting any
     * optional parameters, call the {@link GetStatus#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetStatus#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetStatus(java.lang.Integer id) {
      super(Statusapi.this, "GET", REST_PATH, null, com.appspot.dl_mytimeline.statusapi.model.Status.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetStatus setAlt(java.lang.String alt) {
      return (GetStatus) super.setAlt(alt);
    }

    @Override
    public GetStatus setFields(java.lang.String fields) {
      return (GetStatus) super.setFields(fields);
    }

    @Override
    public GetStatus setKey(java.lang.String key) {
      return (GetStatus) super.setKey(key);
    }

    @Override
    public GetStatus setOauthToken(java.lang.String oauthToken) {
      return (GetStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public GetStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetStatus setQuotaUser(java.lang.String quotaUser) {
      return (GetStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetStatus setUserIp(java.lang.String userIp) {
      return (GetStatus) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer id;

    /**

     */
    public java.lang.Integer getId() {
      return id;
    }

    public GetStatus setId(java.lang.Integer id) {
      this.id = id;
      return this;
    }

    @Override
    public GetStatus set(String parameterName, Object value) {
      return (GetStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "list".
   *
   * This request holds the parameters needed by the statusapi server.  After setting any optional
   * parameters, call the {@link List#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public List list() throws java.io.IOException {
    List result = new List();
    initialize(result);
    return result;
  }

  public class List extends StatusapiRequest<com.appspot.dl_mytimeline.statusapi.model.StatusCollection> {

    private static final String REST_PATH = "statuscollection";

    /**
     * Create a request for the method "list".
     *
     * This request holds the parameters needed by the the statusapi server.  After setting any
     * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
     * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected List() {
      super(Statusapi.this, "GET", REST_PATH, null, com.appspot.dl_mytimeline.statusapi.model.StatusCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public List setAlt(java.lang.String alt) {
      return (List) super.setAlt(alt);
    }

    @Override
    public List setFields(java.lang.String fields) {
      return (List) super.setFields(fields);
    }

    @Override
    public List setKey(java.lang.String key) {
      return (List) super.setKey(key);
    }

    @Override
    public List setOauthToken(java.lang.String oauthToken) {
      return (List) super.setOauthToken(oauthToken);
    }

    @Override
    public List setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (List) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public List setQuotaUser(java.lang.String quotaUser) {
      return (List) super.setQuotaUser(quotaUser);
    }

    @Override
    public List setUserIp(java.lang.String userIp) {
      return (List) super.setUserIp(userIp);
    }

    @Override
    public List set(String parameterName, Object value) {
      return (List) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "remove".
   *
   * This request holds the parameters needed by the statusapi server.  After setting any optional
   * parameters, call the {@link Remove#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public Remove remove(java.lang.Integer id) throws java.io.IOException {
    Remove result = new Remove(id);
    initialize(result);
    return result;
  }

  public class Remove extends StatusapiRequest<Void> {

    private static final String REST_PATH = "status/{id}";

    /**
     * Create a request for the method "remove".
     *
     * This request holds the parameters needed by the the statusapi server.  After setting any
     * optional parameters, call the {@link Remove#execute()} method to invoke the remote operation.
     * <p> {@link
     * Remove#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected Remove(java.lang.Integer id) {
      super(Statusapi.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public Remove setAlt(java.lang.String alt) {
      return (Remove) super.setAlt(alt);
    }

    @Override
    public Remove setFields(java.lang.String fields) {
      return (Remove) super.setFields(fields);
    }

    @Override
    public Remove setKey(java.lang.String key) {
      return (Remove) super.setKey(key);
    }

    @Override
    public Remove setOauthToken(java.lang.String oauthToken) {
      return (Remove) super.setOauthToken(oauthToken);
    }

    @Override
    public Remove setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Remove) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Remove setQuotaUser(java.lang.String quotaUser) {
      return (Remove) super.setQuotaUser(quotaUser);
    }

    @Override
    public Remove setUserIp(java.lang.String userIp) {
      return (Remove) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer id;

    /**

     */
    public java.lang.Integer getId() {
      return id;
    }

    public Remove setId(java.lang.Integer id) {
      this.id = id;
      return this;
    }

    @Override
    public Remove set(String parameterName, Object value) {
      return (Remove) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "update".
   *
   * This request holds the parameters needed by the statusapi server.  After setting any optional
   * parameters, call the {@link Update#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.dl_mytimeline.statusapi.model.Status}
   * @return the request
   */
  public Update update(com.appspot.dl_mytimeline.statusapi.model.Status content) throws java.io.IOException {
    Update result = new Update(content);
    initialize(result);
    return result;
  }

  public class Update extends StatusapiRequest<com.appspot.dl_mytimeline.statusapi.model.Status> {

    private static final String REST_PATH = "status";

    /**
     * Create a request for the method "update".
     *
     * This request holds the parameters needed by the the statusapi server.  After setting any
     * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
     * <p> {@link
     * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.dl_mytimeline.statusapi.model.Status}
     * @since 1.13
     */
    protected Update(com.appspot.dl_mytimeline.statusapi.model.Status content) {
      super(Statusapi.this, "PUT", REST_PATH, content, com.appspot.dl_mytimeline.statusapi.model.Status.class);
    }

    @Override
    public Update setAlt(java.lang.String alt) {
      return (Update) super.setAlt(alt);
    }

    @Override
    public Update setFields(java.lang.String fields) {
      return (Update) super.setFields(fields);
    }

    @Override
    public Update setKey(java.lang.String key) {
      return (Update) super.setKey(key);
    }

    @Override
    public Update setOauthToken(java.lang.String oauthToken) {
      return (Update) super.setOauthToken(oauthToken);
    }

    @Override
    public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Update) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Update setQuotaUser(java.lang.String quotaUser) {
      return (Update) super.setQuotaUser(quotaUser);
    }

    @Override
    public Update setUserIp(java.lang.String userIp) {
      return (Update) super.setUserIp(userIp);
    }

    @Override
    public Update set(String parameterName, Object value) {
      return (Update) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Statusapi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Statusapi}. */
    @Override
    public Statusapi build() {
      return new Statusapi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link StatusapiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setStatusapiRequestInitializer(
        StatusapiRequestInitializer statusapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(statusapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
