/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-04 at 08:04:10 UTC 
 * Modify at your own risk.
 */

package com.dl.mytimeline.autostatusendpoint;

/**
 * Service definition for Autostatusendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AutostatusendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Autostatusendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the autostatusendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://dl-mytimeline.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "autostatusendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Autostatusendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Autostatusendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAutoStatus".
   *
   * This request holds the parameters needed by the autostatusendpoint server.  After setting any
   * optional parameters, call the {@link GetAutoStatus#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetAutoStatus getAutoStatus(java.lang.Long id) throws java.io.IOException {
    GetAutoStatus result = new GetAutoStatus(id);
    initialize(result);
    return result;
  }

  public class GetAutoStatus extends AutostatusendpointRequest<com.dl.mytimeline.autostatusendpoint.model.AutoStatus> {

    private static final String REST_PATH = "autostatus/{id}";

    /**
     * Create a request for the method "getAutoStatus".
     *
     * This request holds the parameters needed by the the autostatusendpoint server.  After setting
     * any optional parameters, call the {@link GetAutoStatus#execute()} method to invoke the remote
     * operation. <p> {@link GetAutoStatus#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAutoStatus(java.lang.Long id) {
      super(Autostatusendpoint.this, "GET", REST_PATH, null, com.dl.mytimeline.autostatusendpoint.model.AutoStatus.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAutoStatus setAlt(java.lang.String alt) {
      return (GetAutoStatus) super.setAlt(alt);
    }

    @Override
    public GetAutoStatus setFields(java.lang.String fields) {
      return (GetAutoStatus) super.setFields(fields);
    }

    @Override
    public GetAutoStatus setKey(java.lang.String key) {
      return (GetAutoStatus) super.setKey(key);
    }

    @Override
    public GetAutoStatus setOauthToken(java.lang.String oauthToken) {
      return (GetAutoStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAutoStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAutoStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAutoStatus setQuotaUser(java.lang.String quotaUser) {
      return (GetAutoStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAutoStatus setUserIp(java.lang.String userIp) {
      return (GetAutoStatus) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetAutoStatus setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAutoStatus set(String parameterName, Object value) {
      return (GetAutoStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAutoStatus".
   *
   * This request holds the parameters needed by the autostatusendpoint server.  After setting any
   * optional parameters, call the {@link InsertAutoStatus#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.dl.mytimeline.autostatusendpoint.model.AutoStatus}
   * @return the request
   */
  public InsertAutoStatus insertAutoStatus(com.dl.mytimeline.autostatusendpoint.model.AutoStatus content) throws java.io.IOException {
    InsertAutoStatus result = new InsertAutoStatus(content);
    initialize(result);
    return result;
  }

  public class InsertAutoStatus extends AutostatusendpointRequest<com.dl.mytimeline.autostatusendpoint.model.AutoStatus> {

    private static final String REST_PATH = "autostatus";

    /**
     * Create a request for the method "insertAutoStatus".
     *
     * This request holds the parameters needed by the the autostatusendpoint server.  After setting
     * any optional parameters, call the {@link InsertAutoStatus#execute()} method to invoke the
     * remote operation. <p> {@link InsertAutoStatus#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.dl.mytimeline.autostatusendpoint.model.AutoStatus}
     * @since 1.13
     */
    protected InsertAutoStatus(com.dl.mytimeline.autostatusendpoint.model.AutoStatus content) {
      super(Autostatusendpoint.this, "POST", REST_PATH, content, com.dl.mytimeline.autostatusendpoint.model.AutoStatus.class);
    }

    @Override
    public InsertAutoStatus setAlt(java.lang.String alt) {
      return (InsertAutoStatus) super.setAlt(alt);
    }

    @Override
    public InsertAutoStatus setFields(java.lang.String fields) {
      return (InsertAutoStatus) super.setFields(fields);
    }

    @Override
    public InsertAutoStatus setKey(java.lang.String key) {
      return (InsertAutoStatus) super.setKey(key);
    }

    @Override
    public InsertAutoStatus setOauthToken(java.lang.String oauthToken) {
      return (InsertAutoStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAutoStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAutoStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAutoStatus setQuotaUser(java.lang.String quotaUser) {
      return (InsertAutoStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAutoStatus setUserIp(java.lang.String userIp) {
      return (InsertAutoStatus) super.setUserIp(userIp);
    }

    @Override
    public InsertAutoStatus set(String parameterName, Object value) {
      return (InsertAutoStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAutoStatus".
   *
   * This request holds the parameters needed by the autostatusendpoint server.  After setting any
   * optional parameters, call the {@link ListAutoStatus#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAutoStatus listAutoStatus() throws java.io.IOException {
    ListAutoStatus result = new ListAutoStatus();
    initialize(result);
    return result;
  }

  public class ListAutoStatus extends AutostatusendpointRequest<com.dl.mytimeline.autostatusendpoint.model.CollectionResponseAutoStatus> {

    private static final String REST_PATH = "autostatus";

    /**
     * Create a request for the method "listAutoStatus".
     *
     * This request holds the parameters needed by the the autostatusendpoint server.  After setting
     * any optional parameters, call the {@link ListAutoStatus#execute()} method to invoke the remote
     * operation. <p> {@link ListAutoStatus#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAutoStatus() {
      super(Autostatusendpoint.this, "GET", REST_PATH, null, com.dl.mytimeline.autostatusendpoint.model.CollectionResponseAutoStatus.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAutoStatus setAlt(java.lang.String alt) {
      return (ListAutoStatus) super.setAlt(alt);
    }

    @Override
    public ListAutoStatus setFields(java.lang.String fields) {
      return (ListAutoStatus) super.setFields(fields);
    }

    @Override
    public ListAutoStatus setKey(java.lang.String key) {
      return (ListAutoStatus) super.setKey(key);
    }

    @Override
    public ListAutoStatus setOauthToken(java.lang.String oauthToken) {
      return (ListAutoStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAutoStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAutoStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAutoStatus setQuotaUser(java.lang.String quotaUser) {
      return (ListAutoStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAutoStatus setUserIp(java.lang.String userIp) {
      return (ListAutoStatus) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAutoStatus setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAutoStatus setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAutoStatus set(String parameterName, Object value) {
      return (ListAutoStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "protectInsertAutoStatus".
   *
   * This request holds the parameters needed by the autostatusendpoint server.  After setting any
   * optional parameters, call the {@link ProtectInsertAutoStatus#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.dl.mytimeline.autostatusendpoint.model.AutoStatus}
   * @return the request
   */
  public ProtectInsertAutoStatus protectInsertAutoStatus(com.dl.mytimeline.autostatusendpoint.model.AutoStatus content) throws java.io.IOException {
    ProtectInsertAutoStatus result = new ProtectInsertAutoStatus(content);
    initialize(result);
    return result;
  }

  public class ProtectInsertAutoStatus extends AutostatusendpointRequest<com.dl.mytimeline.autostatusendpoint.model.AutoStatus> {

    private static final String REST_PATH = "protectInsertAutoStatus";

    /**
     * Create a request for the method "protectInsertAutoStatus".
     *
     * This request holds the parameters needed by the the autostatusendpoint server.  After setting
     * any optional parameters, call the {@link ProtectInsertAutoStatus#execute()} method to invoke
     * the remote operation. <p> {@link ProtectInsertAutoStatus#initialize(com.google.api.client.googl
     * eapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.dl.mytimeline.autostatusendpoint.model.AutoStatus}
     * @since 1.13
     */
    protected ProtectInsertAutoStatus(com.dl.mytimeline.autostatusendpoint.model.AutoStatus content) {
      super(Autostatusendpoint.this, "POST", REST_PATH, content, com.dl.mytimeline.autostatusendpoint.model.AutoStatus.class);
    }

    @Override
    public ProtectInsertAutoStatus setAlt(java.lang.String alt) {
      return (ProtectInsertAutoStatus) super.setAlt(alt);
    }

    @Override
    public ProtectInsertAutoStatus setFields(java.lang.String fields) {
      return (ProtectInsertAutoStatus) super.setFields(fields);
    }

    @Override
    public ProtectInsertAutoStatus setKey(java.lang.String key) {
      return (ProtectInsertAutoStatus) super.setKey(key);
    }

    @Override
    public ProtectInsertAutoStatus setOauthToken(java.lang.String oauthToken) {
      return (ProtectInsertAutoStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public ProtectInsertAutoStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ProtectInsertAutoStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ProtectInsertAutoStatus setQuotaUser(java.lang.String quotaUser) {
      return (ProtectInsertAutoStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public ProtectInsertAutoStatus setUserIp(java.lang.String userIp) {
      return (ProtectInsertAutoStatus) super.setUserIp(userIp);
    }

    @Override
    public ProtectInsertAutoStatus set(String parameterName, Object value) {
      return (ProtectInsertAutoStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "quoteAndInsertAutoStatus".
   *
   * This request holds the parameters needed by the autostatusendpoint server.  After setting any
   * optional parameters, call the {@link QuoteAndInsertAutoStatus#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.dl.mytimeline.autostatusendpoint.model.AutoStatus}
   * @return the request
   */
  public QuoteAndInsertAutoStatus quoteAndInsertAutoStatus(com.dl.mytimeline.autostatusendpoint.model.AutoStatus content) throws java.io.IOException {
    QuoteAndInsertAutoStatus result = new QuoteAndInsertAutoStatus(content);
    initialize(result);
    return result;
  }

  public class QuoteAndInsertAutoStatus extends AutostatusendpointRequest<com.dl.mytimeline.autostatusendpoint.model.AutoStatus> {

    private static final String REST_PATH = "quoteAndInsertAutoStatus";

    /**
     * Create a request for the method "quoteAndInsertAutoStatus".
     *
     * This request holds the parameters needed by the the autostatusendpoint server.  After setting
     * any optional parameters, call the {@link QuoteAndInsertAutoStatus#execute()} method to invoke
     * the remote operation. <p> {@link QuoteAndInsertAutoStatus#initialize(com.google.api.client.goog
     * leapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.dl.mytimeline.autostatusendpoint.model.AutoStatus}
     * @since 1.13
     */
    protected QuoteAndInsertAutoStatus(com.dl.mytimeline.autostatusendpoint.model.AutoStatus content) {
      super(Autostatusendpoint.this, "POST", REST_PATH, content, com.dl.mytimeline.autostatusendpoint.model.AutoStatus.class);
    }

    @Override
    public QuoteAndInsertAutoStatus setAlt(java.lang.String alt) {
      return (QuoteAndInsertAutoStatus) super.setAlt(alt);
    }

    @Override
    public QuoteAndInsertAutoStatus setFields(java.lang.String fields) {
      return (QuoteAndInsertAutoStatus) super.setFields(fields);
    }

    @Override
    public QuoteAndInsertAutoStatus setKey(java.lang.String key) {
      return (QuoteAndInsertAutoStatus) super.setKey(key);
    }

    @Override
    public QuoteAndInsertAutoStatus setOauthToken(java.lang.String oauthToken) {
      return (QuoteAndInsertAutoStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public QuoteAndInsertAutoStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (QuoteAndInsertAutoStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public QuoteAndInsertAutoStatus setQuotaUser(java.lang.String quotaUser) {
      return (QuoteAndInsertAutoStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public QuoteAndInsertAutoStatus setUserIp(java.lang.String userIp) {
      return (QuoteAndInsertAutoStatus) super.setUserIp(userIp);
    }

    @Override
    public QuoteAndInsertAutoStatus set(String parameterName, Object value) {
      return (QuoteAndInsertAutoStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAutoStatus".
   *
   * This request holds the parameters needed by the autostatusendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAutoStatus#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAutoStatus removeAutoStatus(java.lang.Long id) throws java.io.IOException {
    RemoveAutoStatus result = new RemoveAutoStatus(id);
    initialize(result);
    return result;
  }

  public class RemoveAutoStatus extends AutostatusendpointRequest<Void> {

    private static final String REST_PATH = "autostatus/{id}";

    /**
     * Create a request for the method "removeAutoStatus".
     *
     * This request holds the parameters needed by the the autostatusendpoint server.  After setting
     * any optional parameters, call the {@link RemoveAutoStatus#execute()} method to invoke the
     * remote operation. <p> {@link RemoveAutoStatus#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAutoStatus(java.lang.Long id) {
      super(Autostatusendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAutoStatus setAlt(java.lang.String alt) {
      return (RemoveAutoStatus) super.setAlt(alt);
    }

    @Override
    public RemoveAutoStatus setFields(java.lang.String fields) {
      return (RemoveAutoStatus) super.setFields(fields);
    }

    @Override
    public RemoveAutoStatus setKey(java.lang.String key) {
      return (RemoveAutoStatus) super.setKey(key);
    }

    @Override
    public RemoveAutoStatus setOauthToken(java.lang.String oauthToken) {
      return (RemoveAutoStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAutoStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAutoStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAutoStatus setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAutoStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAutoStatus setUserIp(java.lang.String userIp) {
      return (RemoveAutoStatus) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveAutoStatus setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAutoStatus set(String parameterName, Object value) {
      return (RemoveAutoStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAutoStatus".
   *
   * This request holds the parameters needed by the autostatusendpoint server.  After setting any
   * optional parameters, call the {@link UpdateAutoStatus#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.dl.mytimeline.autostatusendpoint.model.AutoStatus}
   * @return the request
   */
  public UpdateAutoStatus updateAutoStatus(com.dl.mytimeline.autostatusendpoint.model.AutoStatus content) throws java.io.IOException {
    UpdateAutoStatus result = new UpdateAutoStatus(content);
    initialize(result);
    return result;
  }

  public class UpdateAutoStatus extends AutostatusendpointRequest<com.dl.mytimeline.autostatusendpoint.model.AutoStatus> {

    private static final String REST_PATH = "autostatus";

    /**
     * Create a request for the method "updateAutoStatus".
     *
     * This request holds the parameters needed by the the autostatusendpoint server.  After setting
     * any optional parameters, call the {@link UpdateAutoStatus#execute()} method to invoke the
     * remote operation. <p> {@link UpdateAutoStatus#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.dl.mytimeline.autostatusendpoint.model.AutoStatus}
     * @since 1.13
     */
    protected UpdateAutoStatus(com.dl.mytimeline.autostatusendpoint.model.AutoStatus content) {
      super(Autostatusendpoint.this, "PUT", REST_PATH, content, com.dl.mytimeline.autostatusendpoint.model.AutoStatus.class);
    }

    @Override
    public UpdateAutoStatus setAlt(java.lang.String alt) {
      return (UpdateAutoStatus) super.setAlt(alt);
    }

    @Override
    public UpdateAutoStatus setFields(java.lang.String fields) {
      return (UpdateAutoStatus) super.setFields(fields);
    }

    @Override
    public UpdateAutoStatus setKey(java.lang.String key) {
      return (UpdateAutoStatus) super.setKey(key);
    }

    @Override
    public UpdateAutoStatus setOauthToken(java.lang.String oauthToken) {
      return (UpdateAutoStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAutoStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAutoStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAutoStatus setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAutoStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAutoStatus setUserIp(java.lang.String userIp) {
      return (UpdateAutoStatus) super.setUserIp(userIp);
    }

    @Override
    public UpdateAutoStatus set(String parameterName, Object value) {
      return (UpdateAutoStatus) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Autostatusendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Autostatusendpoint}. */
    @Override
    public Autostatusendpoint build() {
      return new Autostatusendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AutostatusendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAutostatusendpointRequestInitializer(
        AutostatusendpointRequestInitializer autostatusendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(autostatusendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
